# Generated by Django 4.1 on 2022-08-31 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='city',
        ),
    ]
