# Generated by Django 4.1 on 2022-08-31 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_country_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='pin',
            field=models.CharField(default=0, max_length=4),
        ),
    ]
