# Generated by Django 4.1 on 2022-09-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_alter_account_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pin',
            field=models.CharField(default='6773', max_length=4),
        ),
    ]
