# Generated by Django 4.1 on 2022-09-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0010_remove_transaction_amount_transaction_amount_in_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount_in',
            new_name='amount_received',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='amount_out',
            new_name='amount_sent',
        ),
        migrations.AlterField(
            model_name='account',
            name='pin',
            field=models.CharField(default='8947', max_length=4),
        ),
    ]
