# Generated by Django 4.1 on 2022-09-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0011_rename_amount_in_transaction_amount_received_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='account',
            name='pin',
            field=models.CharField(default='6196', max_length=4),
        ),
    ]
