# Generated by Django 4.1 on 2022-09-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0012_alter_transaction_options_alter_account_pin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='account',
            name='pin',
            field=models.CharField(default='2376', max_length=4),
        ),
    ]
